name: 'Status Overview'
description: 'Keep build status in #2 up to date'
author: 'AlCalzone'
inputs:
  githubToken:
    description: 'The github token to use for authentication'
    required: true
runs:
  using: 'node12'
  main: 'main.js'
