name: Update build status overview

# Only run this on changes to the master branch and daily at 1 AM&PM
on:
  push:
    branches:
      - master
  schedule:
    - cron: '00 01,13 * * *'
  workflow_dispatch: {}

jobs:
  update-status:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Run update action
      uses: actions/github-script@v7
      with:
        github-token: ${{secrets.ALCALZONE_TOKEN}}
        script: |
          const status = require(`${process.env.GITHUB_WORKSPACE}/.github/scripts/status.js`);
          return status({ github, context, core });
